import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body>
        <Navbar></Navbar>
        <main className="bg-[#090d16]">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}


// card color = bg-[#1b2438]
// #101626  = navbar

//  #10b981 = green color

